server:
  port: 9528
spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  instance:
    instance-id: gateway-9528
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

info:
  app.name: yxy_microservicecloud
  company.name: www.yanxianyu.com
  build.artifactId: microservicecloud_zuul_gateway_9528
  build.version: 1.0-SNAPSHOT

zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #多个用"*" ignored-services: "*"
  ignored-services: microservicecloud-dept
  prefix: /springcloud