server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/y1260180780/microservicecloud_config.git
          username: 1260180780@qq.com
          password: a541881421100